version: '3'

networks:
  osbbnet:
    driver: bridge

services:
  db:
    image: postgres
    restart: always
    networks:
      - osbbnet
    env_file:
      - .env
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  migrator:
    image: migrate/migrate
    networks:
      - osbbnet
    volumes:
      - ./osbb-shared/migrations:/migrations
    env_file:
      - .env
    command: ["-path", "./migrations/postgres", "-database",  "postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DB?sslmode=disable", "up"]
    depends_on:
      - db
    restart: on-failure

  osbb-notifications:
    image: github.com/i3odja/osbb/osbb-notifications
    networks:
      - osbbnet
    ports:
      - "9090:9090"
      - "8189:8189"
      - "9999:9999"
    env_file:
      - .env
    build:
      dockerfile: Dockerfile
      context: ./osbb-notifications
    depends_on:
      - db
      - migrator
    restart: on-failure
